//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_first_build.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.NewsImages = new HashSet<NewsImage>();
        }
    
        public int ID { get; set; }
        public string NewsTitle { get; set; }
        public string NewsDesc { get; set; }
        public Nullable<int> MinistryYearID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string MainImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual MinistryYear MinistryYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsImage> NewsImages { get; set; }
    }
}
