//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_first_build.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsImage
    {
        public int ID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual News News { get; set; }
    }
}
